export const PAGE_CATEGORIES = [
    "Print on demand",
    "Personalized products",
    "Mix of everything",
    "Clothes",
    "Car accessories",
    "Pets",
    "Kids",
    "Jewelry",
    "Outdoors/Survival",
    "Home decor",
    "Electronics",
    "Phone cases",
    "Make up",
    "Fitness",
    "Health",
    "Tools",
    "Videos",
    "Health care",
    "Others",
    "Phone program",
    "Computer program",
    "Books",
    "Food",
    "Travel",
    "Real estate",
    "Furniture"
].sort();
